### ISSUE TITLE
When will this tool be finalized?

### ISSUE THREAD

**Issue by Lukashaylik** [TUMFTM/Electric_Machine_Design#1]
Hello dear Team,

I am currently writing my thesis in the field of electric machines and I find this repository highly useful for my work.

Looking at the actual state of this repository, I suppose that it is not still finalized yet and I wanted to ask when the next update is coming? Here my Feedbacks:

1) One of the biggest problem I have encountered so far, is that there are still some functions which are entirely in German.
2) Furthermore, I also wanted to ask if the tool can be used to model current electric machines for the automotive sector. I am asking this, because it appears that in the machine calculation part, the most used source for the calculation (Mue08, which I could not find) is from 2008...
3) Finally the tool is still a bit "Buggy": some configurations/input set lead to completely unrrealistic machine values with regard to torque rotational speed and so on.

Thank you in advance for your help!

**Comment by SvenjaKalt** [comment]
Dear Lukashaylik,

thank you for your feedback. The next update will come sometime around end of November/beginning of December and will include an optimization algorithm as well as interfaces for Longitudinal dynamics simulation and cost calculation.

1. I am currently addressing the problem regarding comments still being in english.
2. The reference is: G. Müller, K. Vogt, B. Ponick, Ed., Berechnung elektrischer Maschinen, 6th ed.: Wiley-VCH Verlag GmbH & Co. KGaA, 2008.
3. This "buggy" part is due to the fact, that the tool is not validated in a broad Torque/speed area, it should work fine for most EVs on the market thou. You need to adjust the settings in the analysis GUI, so that you can set the max. speed for example. Adjusting the Current and Voltage leads to the desired torque and nominal speed.

I hope this helps you out!

best regards
Svenja
